spring.application.name=API-Gateway
server.port=8080
spring.cloud.gateway.routes[0].id=item-service
spring.cloud.gateway.routes[0].uri=http://item-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/items/**

spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://order-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[2].id=payment-service
spring.cloud.gateway.routes[2].uri=http://payment-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/payments/**